name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # or the branch you use for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # You can adjust the Node.js version here

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Build the React app
    - name: Build React app
      run: npm run build

    # Step 5: Deploy to Firebase Hosting
    - name: Deploy to Firebase Hosting
      run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}  # Use your Firebase token
